**Homework 02 - Data from the Web**

In [20]:
# Import libraries
import pandas as pd
import numpy as np

from bs4 import BeautifulSoup
import requests

In [27]:
# URL of IS Academia public access form
ISA_form_url = 'http://isa.epfl.ch/imoniteur_ISAP/!GEDPUBLICREPORTS.filter?ww_i_reportModel=133685247'
ISA_url = 'http://isa.epfl.ch/imoniteur_ISAP/!GEDPUBLICREPORTS.bhtml'

# Some variable used
QUERY_STRING = 'query_string'
EMPTY_DATA_STRING = "**NO_DATA**"

**Retrieve data: how to**

In order to get the data, we need to perform a web crowl on the IS-Academia public plateform. IS-Academia has an online webpage with a form allowing us to download data based on different criteria (e.g. year, semester, ...)

In order to have a convienient way to retrieve data from this form, we create a data structure with all possibilities the form accepted for its filter. The data structure we decided to use is a dictionary:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Filter name  -> <br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Filter value -> Filter value id <br/>

As you can see, the dictionary is actually a dictionary of dictionaries. The first level correponds to the filter name. The second level is all filter values possibles associated with the id.

Exemple:<br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Unité académique  -> <br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Informatique -> 249847 <br/>

Note that the second level will also contain the string to use when creating the query.

In [28]:
# Construction of the form "values -> id" dictionary

# Retrieve HTML page
r  = requests.get(ISA_form_url)
soup = BeautifulSoup(r.text, 'html.parser')

# Filter HTML page to get only the filters
table = soup.find(lambda tag: tag.name == 'table' and tag['id'] == 'filtre')

# Each filter name has its own 'tr'
filter_names = table.findAll('tr')

# The dictionnary to store form "values -> id"
formValues= {}

for filter_name in filter_names:
    # Second level of the dictionary
    dic = {}
    
    # String correspind to the filter name (first level)
    filter_name_string = filter_name.find('th').string
    
    
    # The first entry on the second level is the string to use for the query
    dic[QUERY_STRING] = filter_name.find('select')['name']
    
    
    # Now we iterate over each possibility for this filter
    filter_values = filter_name.findAll(lambda tag: tag.name == 'option' and tag['value'] != "null")
    for v in filter_values:
        # Add each combination of "filter value -> id" to the second level
        dic[v.string] = v['value']
    
    # Add the first level to the dictionary
    formValues[filter_name_string] = dic

formValues

{'Période académique': {'2007-2008': '978181',
  '2008-2009': '978187',
  '2009-2010': '978195',
  '2010-2011': '39486325',
  '2011-2012': '123455150',
  '2012-2013': '123456101',
  '2013-2014': '213637754',
  '2014-2015': '213637922',
  '2015-2016': '213638028',
  '2016-2017': '355925344',
  'query_string': 'ww_x_PERIODE_ACAD'},
 'Période pédagogique': {'Bachelor semestre 1': '249108',
  'Bachelor semestre 2': '249114',
  'Bachelor semestre 3': '942155',
  'Bachelor semestre 4': '942163',
  'Bachelor semestre 5': '942120',
  'Bachelor semestre 5b': '2226768',
  'Bachelor semestre 6': '942175',
  'Bachelor semestre 6b': '2226785',
  'Master semestre 1': '2230106',
  'Master semestre 2': '942192',
  'Master semestre 3': '2230128',
  'Master semestre 4': '2230140',
  'Mineur semestre 1': '2335667',
  'Mineur semestre 2': '2335676',
  'Mise à niveau': '2063602308',
  'Projet Master automne': '249127',
  'Projet Master printemps': '3781783',
  'Semestre automne': '953159',
  'Semestre printemps': '2754553',
  'Stage automne 3ème année': '953137',
  'Stage automne 4ème année': '2226616',
  'Stage printemps 3ème année': '983606',
  'Stage printemps 4ème année': '2226626',
  'Stage printemps master': '2227132',
  'query_string': 'ww_x_PERIODE_PEDAGO'},
 'Type de semestre': {"Semestre d'automne": '2936286',
  'Semestre de printemps': '2936295',
  'query_string': 'ww_x_HIVERETE'},
 'Unité académique': {'Architecture': '942293',
  'Chimie et génie chimique': '246696',
  'Cours de mathématiques spéciales': '943282',
  'EME (EPFL Middle East)': '637841336',
  'Génie civil': '942623',
  'Génie mécanique': '944263',
  'Génie électrique et électronique ': '943936',
  'Humanités digitales': '2054839157',
  'Informatique': '249847',
  'Ingénierie financière': '120623110',
  'Management de la technologie': '946882',
  'Mathématiques': '944590',
  'Microtechnique': '945244',
  'Physique': '945571',
  'Science et génie des matériaux': '944917',
  "Sciences et ingénierie de l'environnement": '942953',
  'Sciences et technologies du vivant': '945901',
  'Section FCUE': '1574548993',
  'Systèmes de communication': '946228',
  'query_string': 'ww_x_UNITE_ACAD'}}

**Retrieve data: build queries**

We made a function in order to create in an easy and intuitive way a query URL. The function uses the dictionary build before to retrive the strings and id to use inside the URL.

In [29]:
''' 
Create an query URL for IS-Academia. The webpage will contain all data about EPFL student 
register for a semester in a specifc year in a section. Note that the function can also 
support the season semester (Spring or Autumn), but its optional (not needed for the homework)
    
@param section  - String for the section of EPFL         e.g. Informatique
@param year     - String for the Academic year.          e.g. 2016-2017
@param semester - The semester of the adacemic career.   e.g. Bachelor semestre 5

@return the url string
'''
def build_query_url(section, year, semester, season=EMPTY_DATA_STRING):
    
    # CONSTANTS TO USE IN THE URL
    url = ISA_url + '?'
    url += 'ww_x_GPS=-1&'
    url += 'ww_i_reportModel=133685247&'
    url += 'ww_i_reportModelXsl=133685270&'
    
    # Add the section 
    v1 = formValues['Unité académique']
    url += v1[QUERY_STRING]+'='+v1[section]+'&'
    
    # Add the year
    v1 = formValues['Période académique']
    url += v1[QUERY_STRING]+'='+v1[year]+'&'
    
    # Add the semester 
    v1 = formValues['Période pédagogique']
    url += v1[QUERY_STRING]+'='+v1[semester]
    
    # If a season is specified, add it to the query
    if (season != EMPTY_DATA_STRING):
        v1 = formValues['Type de semestre']
        url += '&'+v1[QUERY_STRING]+'='+v1[season]
    
    return url

**Retrieve data. From HTML to Dataframe**
Once we have a query URL to make our request, we need to extract the data stored in an HTML table into a Pandas Dataframe.

In [185]:
'''
Retrieve dataframes from the url given
'''
def getDataFrame(url):
    # print(url)
    r  = requests.get(url)
    # print(r.status_code)
    soup = BeautifulSoup(r.text, 'html.parser')

    # Dataframe structure
    header = []        # Will store the header for each column
    content = []       # The content of the data, row by row

    #Student data is stored in the only 'table' in the HTML
    for table in soup.find_all('table'):    
    
        #***************HEADER***********
        # retrieve headers from 'th' tag
        for column_header in table.find_all('th'):
            # Only happend the header if it's not empty 
            # This is also a way to clean the 'th' string we receive from the html table, 
            # because the first 'th' is not a column header
            if column_header.string:    
                header.append(column_header.string)
                      
        #***************CONTENT***********
        # The actual content of the table, the rows
        # Each row represents a student entry
        for students in table.find_all('tr'):
            student_row=[]
            #Each column attribute for a student is stored in a 'td'
            for student_column in students.find_all('td'):    
                s = student_column.string
                # If there is no data for a specific row, replace it by the 'empty_data' variable
                if (not s):
                    student_row.append(EMPTY_DATA_STRING)
                else:
                    student_row.append(s)
                
            if student_row:
                # In the HTML table retrieve from ISAcademia, there is a last 'td' in
                # the HTML table which doesn't correspond to any column. Need to remove it
                student_row.pop()
                content.append(student_row)

    # Create DataFrame.
    df = pd.DataFrame(content, columns=header)

    return df.drop(['Orientation Bachelor','Orientation Master','Spécialisation', 'Filière opt.', 'Mineur', 'Statut', 'Type Echange', 'Ecole Echange'], axis=1)

In [187]:
'''
Build an arry of strings for the range of years defined
'''
def getYearRange(_from, _to):
    diff = _to - _from
    years = []
    for x in range (0, diff):
        years.append(str(_from + x) + '-' + str(_from + x + 1))
        
    return years

In [217]:
'''
Build an array of semesters strings
'''
def bachelorSems(name, number):
    sems = []
    for x in range (1, len(number) + 1):
        sems.append(name + number[x - 1])

    return sems

In [218]:
b_sems = bachelorSems("Bachelor semestre ", ['1'])
b_sems_6 = bachelorSems("Bachelor semestre ", ['6'])

In [219]:
# Range 2007 - 2017 as described in the homework requirement
year = getYearRange(2007, 2017)

In [220]:
# build queries for Bachelor semester 1 2007 ~
queries = []
for x in year:
    for y in b_sems:
        queries.append(build_query_url('Informatique', x, y))   
        
# Build query for Bachelor semester 6 2007 ~        
queries_6 = []
for x in year:
    for y in b_sems_6:
        queries_6.append(build_query_url('Informatique', x, y))

In [221]:
# Array of Bachelor sem1 dataframes
bachelor_student_data = []

for q in queries:
    bachelor_student_data.append(getDataFrame(q))
for y in range (0, len(year)):
    bachelor_student_data[y]['year'] = year[y][:4]

# Array of Bachelor sem6 dataframes
bachelor_student_data_6 = []

for q in queries_6:
    bachelor_student_data_6.append(getDataFrame(q))
for y in range (0, len(year)):
    bachelor_student_data_6[y]['year'] = year[y][:4]

In [250]:
b_sem1_data = pd.concat(bachelor_student_data)
b_sem6_data = pd.concat(bachelor_student_data_6)

In [251]:
# Drop duplicated based of the Sciper column, if duplicate, keep the first occurance (with smaller year, the student might have retaken the semester) 
b_sem1_data = b_sem1_data.drop_duplicates(subset='No Sciper', keep='first')
b_sem6_data = b_sem6_data.drop_duplicates(subset='No Sciper', keep='first')
b_sem1_data = b_sem1_data.set_index('No Sciper')
b_sem6_data = b_sem6_data.set_index('No Sciper')

In [253]:

inner = pd.merge(left=b_sem1_data, right=b_sem6_data.drop(['Nom Prénom', 'Civilité'], axis=1), left_index=True, right_index=True)

inner.shape

inner

           Civilité                          Nom Prénom year_x year_y
No Sciper
169569     Monsieur                   Arévalo Christian   2007   2009
179406     Monsieur                  Baeriswyl Jonathan   2007   2009
179428     Monsieur                     Barroco Michael   2007   2009
179449     Monsieur               Bindschaedler Vincent   2007   2009
178553     Monsieur                  Bloch Marc-Olivier   2007   2009
179426     Monsieur                          Bloch Remi   2007   2009
178271     Monsieur              Boéchat Marc-Alexandre   2007   2009
180731     Monsieur                Bricola Jean-Charles   2007   2009
171619     Monsieur                Buchschacher Nicolas   2007   2009
179157     Monsieur                      Calvert Thomas   2007   2009
178711     Monsieur                        Cino Emanuel   2007   2009
178786     Monsieur                        Coiro Andrea   2007   2009
178656     Monsieur                   Curreli Alexandre   2007   2009
178718     Monsieur                    Dal Mas Gianluca   2007   2009
178706       Madame                 Falbriard Stéphanie   2007   2009
181121     Monsieur                          Frund Loïc   2007   2009
180570     Monsieur                        Habfast Paul   2007   2009
178604     Monsieur                     Haefliger Roger   2007   2009
175190     Monsieur                     Hanser Valérian   2007   2009
181248     Monsieur                      Helfer Etienne   2007   2009
178433     Monsieur                   Leuenberger Johan   2007   2009
181298     Monsieur                        Lütolf Lukas   2007   2009
181076     Monsieur                      Martins Acacio   2007   2009
181115     Monsieur   Miraglia Franco de Carvalho Pedro   2007   2009
180094     Monsieur                         Mirza Elias   2007   2009
181017     Monsieur                       Nötzli Andres   2007   2009
179194     Monsieur                       Obrist Damien   2007   2009
179988       Madame                     Portmann Joëlle   2007   2009
180959     Monsieur                    Restani Stéphane   2007   2009
171195     Monsieur                      Richter Arnaud   2007   2009
...             ...                                 ...    ...    ...
235350     Monsieur                       Rizzello Luca   2013   2015
236522     Monsieur                       Rosset Marius   2013   2015
235746     Monsieur            Soccard Aurélien Tristan   2013   2015
228357     Monsieur                   Subri Guy-Laurent   2012   2015
239124     Monsieur                     Tâche Guillaume   2013   2015
235117     Monsieur  Tournigand Guillaume Nicolas Louis   2013   2015
226658     Monsieur                      Weiskopf Robin   2012   2015
237151     Monsieur                Zbinden Boris Adrien   2013   2015
246671     Monsieur                  Abate Bryan Jeremy   2014   2016
251759     Monsieur                   Alami-Idrissi Ali   2014   2016
249498     Monsieur                       Aoun Leonardo   2014   2016
234551     Monsieur            Bachmann Roman Christian   2014   2016
247328     Monsieur                Beck Johannes Magnus   2014   2016
251758     Monsieur                        Benlalah Ali   2014   2016
250300     Monsieur            Bovel Matthieu Alexandre   2014   2016
249954     Monsieur    Burgelin Clément Louis Alexandre   2014   2016
249996     Monsieur                Coudert Rémi Edouard   2014   2016
239489       Madame                     Evrova Gabriela   2014   2016
246663     Monsieur                 Haefeli Simon Lucas   2014   2016
245511     Monsieur                       Lamonato Yves   2014   2016
250703     Monsieur            Madillo Raphael Frederic   2014   2016
245512     Monsieur           Massemin Lucas Christophe   2014   2016
247855     Monsieur   Mösching Guillaume Edouard Albert   2014   2016
245782     Monsieur                      Perret Thibaud   2014   2016
247233     Monsieur                       Ramirez Lucas   2014   2016
225452     Monsieur                         Resin David   2012   2016
250362     Monsieur              Rigori Valentin Joseph   2014   2016
247680     Monsieur                          Soufi Raja   2014   2016
246532     Monsieur               Vaucher Timoté Pascal   2014   2016
247891     Monsieur                      Weier Philippe   2014   2016

[397 rows x 4 columns]

In [265]:
inner['semester_count'] = inner.apply (lambda row: 2 * (int(row["year_y"]) - int(row["year_x"]) + 1), axis=1)

inner['semester_count'].describe()

count    397.000000
mean       6.372796
std        0.830033
min        6.000000
25%        6.000000
50%        6.000000
75%        6.000000
max       10.000000
Name: semester_count, dtype: float64

In [270]:
madam = inner.loc[inner['Civilité']=='Madame']
madam['semester_count'].describe()

count    29.000000
mean      6.206897
std       0.619868
min       6.000000
25%       6.000000
50%       6.000000
75%       6.000000
max       8.000000
Name: semester_count, dtype: float64